<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-12-16T09:55:34 EET" name="Default suite" finished-at="2021-12-16T09:56:03 EET" duration-ms="28455">
    <groups>
    </groups>
    <test started-at="2021-12-16T09:55:34 EET" name="Default test" finished-at="2021-12-16T09:56:03 EET" duration-ms="28455">
      <class name="curs5.XPathExamples">
        <test-method is-config="true" signature="setUp()[pri:0, instance:curs5.XPathExamples@12d4bf7e]" started-at="2021-12-16T09:55:34 EET" name="setUp" finished-at="2021-12-16T09:55:43 EET" duration-ms="8780" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="xpathLoginExample()[pri:1, instance:curs5.XPathExamples@12d4bf7e]" started-at="2021-12-16T09:55:43 EET" name="xpathLoginExample" finished-at="2021-12-16T09:55:52 EET" duration-ms="8730" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- xpathLoginExample -->
        <test-method signature="testAccountDetails()[pri:2, instance:curs5.XPathExamples@12d4bf7e]" started-at="2021-12-16T09:55:52 EET" name="testAccountDetails" finished-at="2021-12-16T09:55:57 EET" depends-on-methods="curs5.XPathExamples.xpathLoginExample" duration-ms="4667" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://keybooks.ro/account/view-order/1641/] but found [https://keybooks.ro/account/view-order/1674/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://keybooks.ro/account/view-order/1641/] but found [https://keybooks.ro/account/view-order/1674/]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at curs5.XPathExamples.testAccountDetails(XPathExamples.java:51)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAccountDetails -->
        <test-method signature="testShopExamples()[pri:3, instance:curs5.XPathExamples@12d4bf7e]" started-at="2021-12-16T09:55:57 EET" name="testShopExamples" finished-at="2021-12-16T09:55:58 EET" duration-ms="1246" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testShopExamples -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:curs5.XPathExamples@12d4bf7e]" started-at="2021-12-16T09:55:58 EET" name="tearDown" finished-at="2021-12-16T09:56:03 EET" duration-ms="4969" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- curs5.XPathExamples -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
